import logging

# TWITCH SETTINGS
TWITCH_IRC_OAUTH = 'oauth:2zbub42p8ra2wyvihjx59xr4c6gt2b'
TWITCH_IRC_HOST = 'irc.twitch.tv'
TWITCH_IRC_PORT = 6667
TWITCH_BOT_USERNAME = 'test_bot'

# SERVICE SETTINGS
DATABASE = 'strafe.db'
LOGGING_LEVEL = logging.DEBUG

# API SETTINGS
TRACK_SLEEP_PERIOD = 5  # in secs
